vich_uploader:
    db_driver: orm

    mappings:
       demande_images:
           uri_prefix: '%demande_images%'
           upload_destination: '%kernel.project_dir%/public%demande_images%'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
